name: Update CV PDF from Google Docs
permissions:
  contents: write
  pages: write
  
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Every midnight UTC

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download latest CV
        run: curl -L "$CV_PDF_URL" -o public/cv.pdf
        env:
          CV_PDF_URL: ${{ secrets.CV_PDF_URL }}

      - name: Build
        run: |
          npm install
          npm run build

      - name: Deploy CV
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          destination_dir: .
          keep_files: true
